jobs:
  include:
  - stage: test
    services:
    - docker
    before_install:
    - docker build -t apraxos/apraxos .
    script:
    - docker run --rm -v $(pwd):/home/praxis/ apraxos/apraxos /home/praxis/abackup/abackup_test.sh
  - stage: build
    services:
    - docker
    before_install:
    - docker pull asciidoctor/docker-asciidoctor
    script:
    - docker run --rm -v $(pwd)/docs:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf index.adoc
    - tar cvfz abackup.tgz LICENSE docs/index.pdf abackup/abackup.sh abackup/backup_exclude.cfg abackup/LICENSE abackup/backup.cfg.*
  - stage: GitHub Release
    deploy:
      provider: releases
      api_key:
        secure: uIR/CAFoK2ypEGaMUXPIXr8w4O9PaH6uGWVnfVNi/3AHh8AhgitrIC1AdLVEUMZNkuO75GJboSTBVpE69zJd+j8kDgCxnk5/6X+XSnMD4vmsDONvpUlq2hC7g7/CxoN7poDyM8r6Vv+L9wmzLhOVNlmKfPyMqG/I/pss2eezh9oh70JEzgl+AZ5SXcE8+SXi+grymb/31ZDR9PJeozlRF5wHMQLlpstrNQberVfI9NYN+fTfTFzuob8EUVfsNEtKIs+X16knzuzyXSm4RwIV2d8l52OPhXgXtj1XnUJqPQI3MTNeB3C0knTIgvwNdt8j6GNZeV60lAP4cpAe5DG6cLNO624jFpUKWawLYnO44/0lT/MVlfJDK27Mwh1Hg7dEE6sWgp1hck6Muqawr5sdds+K4UesRTc9dwrNd0tJcw3XmB83fpCeJWiBpIyrRltH2oEG1W0WlEBsNLvw6YRZDdTmbATlrFDZQh2jGWhYK5mMBEpGTEFoeYQhSMoeOZbAorkES1XnS1PO0m45qXZC3zxFAPWcRzvb8hVfO/ChzTYMzmxyaLt8CNzkm5fDkhtOpDq9DvrP8eaN6S6UEHgZnbFiga5vJ5C25cNkMzF77RPFBw/83VltpsGEwM2uQ2XXNGB/AyJhlqY42cz3WkxtHiGcfV4Rieo0BtJ533jTI9w=
      file: apraxos.tgz
      on:
        repo: apraxos/apraxos
