=== abackup - apraxos Backup

.Die Anforderungen
- Inkrementelle tägliche Sicherung: Viele Stände, wenig Speicherbedarf
- Konsistente Sicherung: Ein Backup wird angestoßen, wenn kein apraxos Prozess läuft 
- Überprüfbare Backups (Zeitstempel, Fehlerlogs)
- Anstoßen der Sicherung vor Apraxos Updates
- Schutz vor Verschlüsselungstrojanern
- Berücksichtung von Brandabschnitten
- Es sollte in wenigen Minuten erstellt sein
- Daten verlassen, auf welchem Medium auch immer, die Praxis nur verschlüsselt
- Bisher nicht berücksichtigt: beweissicheren Archivierungsrichtlinien 

==== abackup.sh "Command Line Interface"

.Fehlerbehandlung:
- exit != 0 falls ein Fehler erkannt wurde
- Fehlerausgabe aktuell in stdout (ToDo: errout?)

.abackup.sh run
- rsync zur rollierenden Wochentagssicherung und/oder
- rsync zur inkrementellen täglichen Sicherung 
- das Fehler- und Statusprotokoll wird gespeichert
- ein backup_timestamp wird erzeugt

.abackup.sh status
- listet Informationen zum Backupzeitpunkt und Fehler 
- zeigt Anzahl neuerer Dateien
- exit status 0 falls das Backup aktuell ist

.abackup.sh changes
- listet Dateien, die neuer sind als das letzte Backup

.abackup.sh install
- tbd

.abackup.sh uninstall
- tbd

_Wie mache ich jetzt ein Backup?_

[source,bash]
----
abackup.sh run
----

_Wie prüft man ob das Backup ok ist?_

[source,bash]
----
login abackup
abackup.sh status
----

==== Konfiguration

_Wie konfiguriere ich ein einfaches inkrementelles platzsparendes Backup mit Tagesstempel?_ 

.backup.cfg 
----
sourcefolders=~/a/
_today=$(date +%Y-%m-%d-%H%M)
destfolders_incr=/media/usb-backup/${_today}/
logfolder=/media/usb-backup/log
----

_Wie schließe ich Files vom Backup aus?_

Das exclude File ``backup_exclude.cfg`` beinhaltet die für das Apraxos Backup bekannten unnötigen Files.

.backup_exclude.cfg 
----
./backup_timestamp
a/*.bak
a/*.ink
a/*.cdx
...
----

_Wo finde ich weitere Beispiele?_

* backup.cfg.minimal: ein einfaches Standard Beispiel
* backup.cfg.test: ein komplexes Beispiel, welches die meisten Konfigurationsmöglichen beinhaltet
* backup.cfg.remotessh: ein einfaches Beipsiel, welches einen entfernten SSH Server als Backup Medium nutzt 
* backup.cfg.nfs: ein fortgeschrittenes Beispiel, welches zum Backup einen großen Fileshare nutzt und zusätzlich ein rollierendes Backup ausführt lokal und auf einen entfernten SSH Server durchführt. Es wird hier auch geprüft, ob der Share wirklich gemountet ist. 

==== abackup.sh test

[source,bash]
----
abackup_test.sh
----
